name: pdfast
version: 0.1.0.0
github: "felixnaredi/pdfast"
license: BSD3
author: "Felix Naredi"
maintainer: "felixnaredi@gmail.com"
copyright: "Felix Naredi"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/felixnaredi/pdfast#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - hspec
  - mtl
  - parsec
  - QuickCheck

library:
  source-dirs: src

tests:
  pdfast-unit-test:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pdfast
